apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  replicas: 1
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      labels:
        role: app
    spec:
      containers:
      - name: front
        image: eugeele/covachapp:frontend
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: front
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
  selector:
    role: app