apiVersion: networking.k8s.io/v1
kind: Ingress  
metadata:  
  name: example-ingress  
  annotations:  
    nginx.ingress.kubernetes.io/rewrite-target: /$1 
spec: 
  rules:  
    - host: 
      http: 
        paths:  
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 82
          - path: /login
            pathType: Prefix
            backend:
              service:
                name: auth-svc
                port:
                  number: 8000
          - path: /search
            pathType: Prefix
            backend:
              service:
                name: products-service
                port:
                  number: 8001            