apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: hola
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nginx
      app: all
  template:
    metadata:
      labels:
        role: nginx
    spec:
      containers:
      - name: nginx
        image: eugeele/covachapp:nginx
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: hola
spec:
  type: NodePort
  ports:
  - port: 81
    targetPort: 80
    nodePort: 30001
  selector:
    role: nginx
    app: all