apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-consumer
  namespace: hola
spec:
  replicas: 1
  selector:
    matchLabels:
      role: search-c
  template:
    metadata:
      labels:
        role: search-c
    spec:
      containers:
      - name: search-consumer
        image: gfs5/challenge:search-con
        # ports:
        # - containerPort: 9000

---
# apiVersion: v1
# kind: Service
# metadata:
#   name: search-consumer
#   namespace: hola
# spec:
#   ports:
#   - port: 9000
#     targetPort: 9000
#   selector:
#     role: search-c
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-db
  namespace: hola
spec:
  replicas: 1
  selector:
    matchLabels:
      role: search-c
  template:
    metadata:
      labels:
        role: search-c
    spec:
      containers:
      - name: search-db
        image: mongo:4.4.4
        volumeMounts:
        - name: db-data
          mountPath: '/data/db'
        - name: db-config
          mountPath: '/data/configdb'
        ports:
        - containerPort: 27017
      volumes:
      - name: db-data
        emptyDir: {}
      - name: db-config
        emptyDir: {}