apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-consumer
  namespace: hola
spec:
  replicas: 1
  selector:
    matchLabels:
      role: search-c
      app: all
  template:
    metadata:
      labels:
        role: search-c
    spec:
      containers:
      - name: search-consumer
        image: eugeele/covachapp:search-consumer
        # ports:
        # - containerPort: 9000

---
# apiVersion: v1
# kind: Service
# metadata:
#   name: search-consumer
#   namespace: hola
# spec:
#   ports:
#   - port: 9000
#     targetPort: 9000
#   selector:
#     role: search-c