apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: hola
spec:
  replicas: 1
  selector:
    matchLabels:
      role: auth
  template:
    metadata:
      labels:
        role: auth
    spec:
      containers:
      - name: auth-service
        image: gfs5/challenge:auth
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: auth-secrets        
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: hola
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    role: auth
    app: all

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-db
  namespace: hola
spec:
  replicas: 1
  selector:
    matchLabels:
      role: auth
  template:
    metadata:
      labels:
        role: auth
    spec:
      containers:
      - name: auth-db
        image: postgres:14.1-alpine3.15
        envFrom:
          - secretRef:
              name: auth-secrets      
        ports:
        - containerPort: 5432