apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: hola
spec:
  replicas: 1
  selector:
    matchLabels:
      role: front
  template:
    metadata:
      labels:
        role: front
    spec:
      containers:
      - name: front
        image: gfs5/challenge:front
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: front-secrets
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: hola
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    role: front

---