apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nginx
  template:
    metadata:
      labels:
        role: nginx
    spec:
      containers:
      - name: nginx
        image: gfs5/challenge:cova-nginx
        imagePullPolicy: Always        
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: app
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30100    
  selector:
    role: nginx

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      role: front
  template:
    metadata:
      labels:
        role: front
    spec:
      containers:
      - name: front
        image: gfs5/challenge:cova-front
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: front-secrets        
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: app
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30050
  selector:
    role: front

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      role: auth
  template:
    metadata:
      labels:
        role: auth
    spec:
      containers:
      - name: auth-service
        image: gfs5/challenge:cova-auth
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: auth-secrets  
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: app
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30110
  selector:
    role: auth


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-db
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      role: auth-db
  template:
    metadata:
      labels:
        role: auth-db
    spec:
      containers:
      - name: auth-db
        image: postgres:14.1-alpine3.15
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: auth-secrets         
        ports:
        - containerPort: 5432
---

apiVersion: v1
kind: Service
metadata:
  name: auth-db
  namespace: app
  labels:
    role: auth-db
spec:
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    role: auth-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-service
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      role: products-s
  template:
    metadata:
      labels:
        role: products-s
    spec:
      containers:
      - name: products-service
        image: gfs5/challenge:cova-products
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: products-secrets        
        ports:
        - containerPort: 8001

---
apiVersion: v1
kind: Service
metadata:
  name: products-service
  namespace: app
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
    nodePort: 30120
  selector:
    role: products-s


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-db
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      role: products-db
  template:
    metadata:
      labels:
        role: products-db
    spec:
      containers:
      - name: products-db
        image: postgres:14.1-alpine3.15
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: products-secrets
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: products-db
  namespace: app
  labels:
    role: products-db
spec:
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    role: products-db
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-consumer
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      role: search-c
  template:
    metadata:
      labels:
        role: search-c
    spec:
      containers:
      - name: search-consumer
        image: gfs5/challenge:cova-search-consumer
        env:
        - name: IS_CONSUMER
          value: "1"
        envFrom:
          - secretRef:
              name: search-secrets         
        imagePullPolicy: Always

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      role: search-s
  template:
    metadata:
      labels:
        role: search-s
    spec:
      containers:
      - name: search-service
        image: gfs5/challenge:cova-search-service
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: search-secrets         
        ports:
        - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: app
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
    nodePort: 30130
  selector:
    role: search-s

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-db
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      role: search-db
  template:
    metadata:
      labels:
        role: search-db
    spec:
      containers:
      - name: search-db
        image: mongo:4.4.4
        # container_name: search-db
        imagePullPolicy: Always
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: root
        - name: MONGO_INITDB_DATABASE
          value: test
        volumeMounts:
        - name: db-data
          mountPath: '/data/db'
        - name: db-config
          mountPath: '/data/configdb'
        ports:
        - containerPort: 27017
      volumes:
      - name: db-data
        emptyDir: {}
      - name: db-config
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: search-db
  namespace: app
  labels:
    role: search-db
spec:
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  selector:
    role: search-db