apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-service
  namespace: hola
spec:
  replicas: 1
  selector:
    matchLabels:
      role: products
  template:
    metadata:
      labels:
        role: products
    spec:
      containers:
      - name: products-service
        image: gfs5/challenge:products
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: products-secrets        
        ports:
        - containerPort: 8001

---
apiVersion: v1
kind: Service
metadata:
  name: products-service
  namespace: hola
spec:
  ports:
  - port: 8001
    targetPort: 8001
  selector:
    role: products
    app: all    

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-db
  namespace: hola
spec:
  replicas: 1
  selector:
    matchLabels:
      role: products
  template:
    metadata:
      labels:
        role: products
    spec:
      containers:
      - name: postgres-data
        image: postgres:14.1-alpine3.15
        envFrom:
          - secretRef:
              name: products-secrets
        ports:
        - containerPort: 5433
