apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  namespace: hola
spec:
  replicas: 1
  selector:
    matchLabels:
      role: search-s
      app: all
  template:
    metadata:
      labels:
        role: search-s
        app: all
    spec:
      containers:
      - name: search-service
        image: gfs5/challenge:search-s
        envFrom:
          - secretRef:
              name: search-secrets      
        ports:
        - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: hola
spec:
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    role: search-s
    app: all

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-consumer
  namespace: hola
spec:
  replicas: 1
  selector:
    matchLabels:
      role: search-c
  template:
    metadata:
      labels:
        role: search-c
    spec:
      containers:
      - name: search-consumer
        image: gfs5/challenge:search-con
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: search-secrets
        env:
          - name: IS_CONSUMER
            value: 1
        

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-db
  namespace: hola
spec:
  replicas: 1
  selector:
    matchLabels:
      role: search-c
  template:
    metadata:
      labels:
        role: search-c
    spec:
      containers:
      - name: search-db
        image: mongo:4.4.4
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: root
        - name: MONGO_INITDB_DATABASE
          value: test
        volumeMounts:
        - name: db-data
          mountPath: '/data/db'
        - name: db-config
          mountPath: '/data/configdb'
        ports:
        - containerPort: 27017
      volumes:
      - name: db-data
        emptyDir: {}
      - name: db-config
        emptyDir: {}