name: CI Build Docker-Frontend
on:
  push:
    branches:
      - 'main'
env:
  NEXT_PUBLIC_AUTH_SERVICE_BASE_URL: http://localhost:8000
  NEXT_PUBLIC_PRODUCT_SERVICE_BASE_URL: http://localhost:8001
  NEXT_PUBLIC_SEARCH_SERVICE_BASE_URL: http://localhost:9000
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        file: ./../docker/Dockerfile.next
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/challenge:cova-front
