name: CI Build Docker-Frontend
on:
  push:
    branches:
      - 'main'
    # paths:
    #   - frontend/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v2
      
    - name: ChangeVariables
      uses: falnyr/replace-env-vars-action@master
      env:
        NEXT_PUBLIC_AUTH_SERVICE_BASE_URL: ${{ secrets.AUTH_URL}}
        NEXT_PUBLIC_PRODUCT_SERVICE_BASE_URL: ${{ secrets.PRODUCT_URL}}
        NEXT_PUBLIC_SEARCH_SERVICE_BASE_URL: ${{ secrets.SEARCH_URL}}
      with:
        filename: ./frontend/.env

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        file: ./docker/Dockerfile.next
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/challenge:cova-front
